.stylelintrc
Restores the stylelint config to disable "dollar-variable-default"
=> Fixes #14 - restore stylelint dollar-variable-default

.github/workflows/review-site.yml
Followup from #54 
Fixed yaml syntax of GitHub actions `review-site.yml` workflow file.  I believe this _should_ allow the workflow to be triggered when code is merged into master.
=> #58: Various review-site workflow improvements.

.github/workflows/cdn-deploy.yml, scripts/build-cdn-assets.sh
This PR adds a github action to deploy a built copy of Arizona Bootstrap to cdn.digital.arizona.edu on when a new semver tag is pushed of when changes are merged to master. It also updates the `latest` path whenever a new semver tag is pushed.
=> Add action to build and deploy CDN assets

package.json
An environment variable passed to Jekyll with the `--host` command-line option can override the hard-coded default, potentially revealing a demo site built within a Docker container to the outside world.
Issue #52 
Setting `-e "UAZ_HOST=0.0.0.0"` as a command-line option to docker run revealed the demo site without needing config file changes. Omitting this option restored the default `localhost` setting.
=> Provide an environment variable to override the default host name — Fixes #52

site/docs/0.0/components/collapse.md
Fixes #79 by removing the h3 from the accordion example, which removes the excess margin that shouldn't be there.
=> Fixes #79 - Remove h3 from accordion example

.github/workflows/release.yml, package-lock.json, package.json
This PR adds a github action that facilitates creating a new release of Arizona Bootstrap.
To trigger this action, update the version within package.json and package-lock.json by running `npm version 0.0.3` and opening a PR with the updates. Once the PR is merged to master, a new release will be generated based on the version number specified in package.json.
Open questions:
=> Bootstrap Release Action

.github/workflows/release.yml
Since tags created by actions/create-release@v1 don't trigger out cdn-deploy.yml action, this PR copies the steps from cdn-deploy.yml into the realease.yml action as a workaround. I still think we should investigate ways to keep the release action a little more lean, but this should work for now.
=> CDN Deploy Workaround

.github/dependabot.yml
This PR adds a config file for github dependabot.
Adding this dependabot config will generate a PR every Monday if there are available updates for our dependencies. We should still get the dependabot security update PRs as they become available.
For more info, see https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates
=> Add weekly dependabot checks for new packages

_config_template.yml
Fixes incorrect CDN paths in Jekyll config template causing bad URLs to get rendered in the docs.
=> Closes #188: Fixed CDN asset paths in _config_template.yml.

.github/workflows/lint.yml, .github/workflows/review-site.yml, package-lock.json, scripts/build-container.sh, site/layouts/partials/scripts.html
Review and documentation sites for Arizona Bootstrap include a prefix (like `bug/261`) in the URLs for pages and their linked resources, but Twitter Bootstrap does not use this. Arizona Bootstrap had modified the code copied from https://github.com/twbs/bootstrap/blob/v4.6.0/site/layouts/partials/stylesheet.html to account for this, but had not yet made the analogous changes to scripts.html. Note: this PR is based on the issue/258 branch, not main, so also includes the changes that improve package-lock.json file handling.
Closes #261
=> Closes #261: Allow .js file references to use base URL settings.

site/layouts/partials/home/masthead-followup.html, site/layouts/partials/home/masthead.html
This doubles as the trivial change that can test issues with the manually triggered Arizona Bootstrap release process.
Closes #263
=> Closes #263: Adjust the Hugo whitespace handling in .Site.Title references.

scss/_custom-styles.scss, site/content/docs/2.0/migration.md, site/content/docs/2.0/utilities/column-split.md, site/data/nav.yml
Closes #275 
Shoshana's work on the Topics footer menu block is reliant on the two-col-menu class to split the menu into 2 columns. Adding a more generic class (and similar classes) to Arizona Bootstrap will allow this feature to be used in more than just the footer menu block.
- 2-col-split
- 3-col-split
- 4-col-split
- column-count: 2
- column-count: 3
- column-count: 4
- https://review.digital.arizona.edu/arizona-bootstrap/issue/275/docs/2.0/migration/#footer-menu
- https://review.digital.arizona.edu/arizona-bootstrap/issue/275/docs/2.0/utilities/column-split/
=> #275 Add col-split utility classes

scss/_custom-styles.scss, site/content/docs/2.0/utilities/column-split.md
Closes #278 
This PR adds the following classes and updates the Arizona Bootstrap documentation.
- split-sm-2-col
- split-md-2-col
- split-lg-2-col
- split-sm-3-col
- split-md-3-col
- split-lg-3-col
- split-sm-4-col
- split-md-4-col
- split-lg-4-col
Review site: https://review.digital.arizona.edu/arizona-bootstrap/issue/278/docs/2.0/utilities/column-split/
=> #278 Add new classes and update documentation

scss/_custom-variables.scss, scss/_navbar-offcanvas.scss, scss/_navbar.scss
Closes #281
Changes to more closely match QS1 include
- Updating main nav to be all uppercase
- Adding top and bottom borders
- Reduced x axis padding
- Updated active background color to span full height
- Updated dropdown arrow to stay on right regardless of word wrap
Review site: https://review.digital.arizona.edu/arizona-bootstrap/issue/281/docs/2.0/components/navbar-off-canvas/
=> Navbar style updates to match QS1 - uppercase, padding, borders (Closes #281)

scss/_collapse.scss
This PR makes two changes to the accordion styles in Bootstrap:
- Adds text-transform: none to the _collapse.scss file to keep the accordion headings regular casing not uppercase
- Adds the arrows on the accordion with the Material Icons Sharp
In testing on the review site, I did not see the reported overlap issue between long headings and the arrows. That may need to be addressed separately in Quickstart.
Review site: https://review.digital.arizona.edu/arizona-bootstrap/issue/291/docs/2.0/components/collapse/
Thanks to @danahertzberg for help during the workshop on how to do bootstrap changes and design input.
=> Closes #291 Updating accordion styles

scss/_custom-styles.scss, scss/_text.scss, site/content/docs/2.0/utilities/text.md
This PR creates a custom of class .text-hyphen to set hyphens: auto. 
SASG reported a problem with words breaking without hyphens in #243. Dana and I were not able to recreate their exact issue, but did not that exceptionally long words can break this way if they are longer than the column size (particularly when there are four cards on a page with sidebar nav).
The .text-hyphen class can be used sparingly in these cases to allow for auto hyphenation of singe words. The documentation for Text Utilities has been updated with an example and also the caution that this class should not be used on paragraphs or longer spans of text.
Review site: https://review.digital.arizona.edu/arizona-bootstrap/issue/243/docs/2.0/utilities/text/
=> Closes #243: Adding class to auto hyphenate long words

scss/_nav.scss
Decision was made in wed workshop to add is-active class to azbs, after checking bs upstream for conflicts, and realizing that drupal adds is-active via javascript and fixing it would be heavier than just adding it to azbs
Also considered adding it to drupal styles.css, but opted to add to azbs instead.
=> Fixes #318 active state of links in ua_quickstart.

scss/_custom-styles.scss
This PR adds custom padding and a border bottom to the .figure-caption class (matching QS1 styles)
Review site: https://review.digital.arizona.edu/arizona-bootstrap/issue/322/docs/2.0/content/figures/
=> Closes #322: Adding .figure-caption styles

site/content/docs/2.0/extend/icons.md, site/content/docs/2.0/getting-started/introduction.md, site/layouts/partials/stylesheet.html
The list of Arizona-specific icons and their corresponding classes are now viewable on the Arizona Bootstrap documentation site under Extend -> Icons.
=> Closes #208: Integrate the Arizona-specific icons into Arizona Bootstrap

site/content/docs/2.0/backwards-compatibility.md, site/content/docs/2.0/deprecated.md, site/content/docs/2.0/migration.md
Correcting an omission in the documentation, which didn't make it into the latest release.
=> Closes #380: Document the changes from UA Bootstrap in hollow buttons.

site/content/docs/2.0/components/dropdowns.md, site/content/docs/2.0/components/popovers.md, site/content/docs/2.0/components/tooltips.md, site/content/docs/2.0/examples/navbar/index.html, site/content/docs/2.0/getting-started/browsers-devices.md, site/content/docs/2.0/getting-started/color-contrast.md, site/content/docs/2.0/migration.md, site/data/browser-features.yml, site/data/slack-channels.yml, site/layouts/partials/bugify.html
Changed references to `bootstrap.bundle.min.js` and `bootstrap.bundle.js` with `arizona-bootstrap.bundle.min.js` and `arizona-bootstrap.bundle.js` everywhere.
Fixed this issue link https://github.com/twbs/bootstrap/issues/4215 on https://review.digital.arizona.edu/arizona-bootstrap/issues/459-fix-broken-links/docs/2.0/components/popovers/#options
Fixed this issue link https://github.com/twbs/bootstrap/issues/4215 on https://review.digital.arizona.edu/arizona-bootstrap/issues/459-fix-broken-links/docs/2.0/components/tooltips/#options
Fixed navbar logo here: https://review.digital.arizona.edu/arizona-bootstrap/issues/459-fix-broken-links/docs/2.0/examples/navbar/
Looks like the main logo is still broken.
Removed a bunch of issue links that no longer exist
=> Closes #459 Fixing broken links in arizona bootstrap docs.

.github/workflows/review-site.yml
This PR is targeting @mmunro-ltrr's PR branch (#565). 
@mmunro-ltrr I might be missing something obvious but it seems to me that the `git restore package-lock.json` step that is failing in the review site actions workflow on your new PR might not be necessary at all (?).
=> Remove unnecessary(?) git restore package-lock.json step.

scss/_breadcrumb.scss
Closes #562 
Motivation is to reduce prominence on breadcrumbs now that the main nav is not uppercase. Removing hover style and lightening the link weight achieves this goal.
=> Closes #562: Update breadcrumb styles

site/content/docs/2.0/getting-started/contents.md, site/content/docs/2.0/getting-started/webpack.md
The Hugo issue has extensive discussion, but a trivial fix seems applicable in this case.
https://github.com/gohugoio/hugo/issues/6081#issuecomment-633147234
This is needed before the next Arizona Bootstrap release, although only the documentation is affected.
=> Closes #580: Change the Hugo shortcode delimiter in headings that end up in the ToC.

Dockerfile, package-lock.json
Alternative fix/workaround for local build issues affecting M1 Macs (#601)
=> Closes #601: Force Docker containers to use amd64 for now.

README.md
Closes #647 
This should be included in the last release to update the "main" bucket `https://cdn.digital.arizona.edu/lib/arizona-bootstrap/main` in our CDN.
=> Closes #647 Announce deprecation of main and latest CDN buckets

.github/workflows/cdn-deploy-head.yml, .github/workflows/cdn-deploy-release.yml, .github/workflows/release.yml, .github/workflows/review-site.yml
This PR updates the community actions used by Arizona Bootstrap to reference major versions. Notice, this also updates the [docker setup action](https://github.com/docker/setup-buildx-action) from `v1` to `v2`. Version 2 of that action released in May of 2022.
=> Update Github Actions to use major versions

.github/dependabot.yml
Enable dependabot alerts for Github actions. Closes #652
=> Closes #652: Add dependabot support for Github actions & Dockerfile

site/data/slack-channels.yml
Parent issue az-digital/az_quickstart#2331
=> az-digital/az_quickstart#2331 Change slack channel names from azdigital-general to azdigital-support

site/content/docs/2.0/about/get-involved.md, site/data/slack-channels.yml
Parent issue: https://github.com/az-digital/az_quickstart/issues/2330
=> az-digital/az_quickstart#2330 Change slack channel names from friday-meetings to azdigital-meetings

.github/dependabot.yml
Copied from https://github.com/twbs/examples/blob/main/.github/dependabot.yml
I believe this would mean that only 2 dependabot PRs would be created for each of our release branches each week.  One for production dependencies and one for dev dependencies.
=> Closes #1179: Added groups to dependabot config.

Dockerfile, package-lock.json
Manual updates to the LTS version of Node.js used here, and npm-check-updates. In addition to the incidental changes to package-lock.json, there should be a change to the `update-deps` script in package.json that invokes the global installation of npm-check-updates from the Docker image, but that's a different issue.
=> Closes #1227; manually bump the version numbers within the Dockerfile.

site/assets/scss/_custom-docs.scss, site/content/docs/5.0/backwards-compatibility.md, site/data/sidebar.yml
This PR does the following:
- Adds a Backwards Compatibility page with boilerplate text: we can add to this page as we continue development of Arizona Bootstrap 5.
- Updates the docs sidebar nav to add a link to the new page.
- Adds a little custom styling for the sidebar nav.
Questions:
1. Should we go ahead and remove the Deprecated page as part of this PR?
https://review.digital.arizona.edu/arizona-bootstrap/issue/1452
=> Closes #1452: Add Backwards Compatibility page to 5.x docs

site/content/docs/5.0/backwards-compatibility.md
https://review.digital.arizona.edu/arizona-bootstrap/issue/1477/docs/5.0/backwards-compatibility/
I have slightly modified [the old Accordion text](https://review.digital.arizona.edu/arizona-bootstrap/issue/1477/docs/5.0/backwards-compatibility/) as a starter. Unfortunately, adding in this code example demonstrates that our current accordion implementation is NOT backwards compatible. Follow up issue incoming...
=> Closes #1477: Add old accordion implementation details to backwards compatibility page in V5

.github/workflows/review-site.yml, .gitignore
2.x version of #1521 
Closes #1497 (for 2.x)
- Adds `/dist` to .gitignore
- Updates review site workflow to skip updating /dist assets in PR branches
- Adds `-f` argument to `git add` command in review site workflow step to override gitignore in main/2.x branches
=> Closes #1497: Add /dist to gitignore, don't update /dist assets in PR branches automatically. (2.x)

.github/workflows/review-site.yml
Closes #1524
Updated review site workflow steps that push dist assets to be more like create release workflow in Quickstart (where we also push automated commits)
=> Closes #1524: Use different GH token for pushing dist assets in review site workflow.

.github/workflows/release.yml
Removes hard-coded reference to 2.x in release workflow that would prevent 5.x releases from working.
=> Closes #1508: Remove hard-coded 2.x reference in release workflow in preparation for creating 5.x releases.

.github/workflows/cdn-deploy-head.yml
We should only be triggering the workflow to update CDN assets for main/2.0.x if there are changes to dist files.
=> Closes #1528: Only update CDN assets if /dist was updated.

scss/arizona-bootstrap.scss
Moves imports of our deprecated scss to the top of the list of Arizona Bootstrap imports.
- #1533
- Confirm deprecated accordion styling is maintained: https://review.digital.arizona.edu/arizona-bootstrap/issue/1533/docs/5.0/backwards-compatibility/
- Confirm deprecated `.nav-tabs-lg` styling is maintained (e.g., using DevTools to add the class): https://review.digital.arizona.edu/arizona-bootstrap/issue/1533/docs/5.0/components/navs-tabs/#tabs
=> Closes #1533: Move our deprecated scss to the top of the list of Arizona Bootstrap imports

scss/override/_forms.scss, site/content/docs/5.0/forms/input-group.md
This PR:
- Adds styling overrides for input group buttons to revert to styling from upstream Bootstrap.
- Restores some overrides for large and small `.col-form-label` classes.
- Updates the Input Groups docs page with a more appropriate button style.
- #1405
- Confirm the button changes here: https://review.digital.arizona.edu/arizona-bootstrap/issue/1405/docs/5.0/forms/input-group/#button-addons ([compare with upstream Bootstrap](https://getbootstrap.com/docs/5.3/forms/input-group/#button-addons))
- Confirm the form label styling here (including the sub-section): https://review.digital.arizona.edu/arizona-bootstrap/issue/1405/docs/5.0/forms/layout/#horizontal-form ([compare with upstream Bootstrap](https://getbootstrap.com/docs/5.3/forms/layout/#horizontal-form))
1. #1252 changed the …
=> Closes #1405: Update input groups for Arizona Bootstrap 5

build/rollup.config.mjs, site/assets/js/partials/snippets.js
Still noticing `Uncaught ReferenceError: bootstrap is not defined` console errors when reviewing #1547 (specifically on https://review.digital.arizona.edu/arizona-bootstrap/issue/1496/docs/5.0/components/modal/).
We should be referencing our global `arizona-bootstrap` but `arizona-bootstrap` is not a valid name for an object reference (variable name) in JS so this updates the rollup config that controls that and some remaining references in the docs JS files.
=> Fix remaining Uncaught ReferenceError: bootstrap is not defined errors (targeting issue/1496)

scss/custom/_callouts.scss, site/content/docs/5.0/backwards-compatibility.md, site/content/docs/5.0/components/callouts.md
This PR does the following:
- Adds callout-info back to the contextual section of the Callouts page
- Keeps the heading the same color as the body, as with the other contextual callouts
- Adds a note to the Contextual (Theme) section that any brand color may be used for informational purposes
- Removes `callout-info` information from the Backwards Compatibility page since it is no longer a removed callout variant
https://review.digital.arizona.edu/arizona-bootstrap/issue/1552/docs/5.0/components/callouts/
=> Closes #1552: Add callout-info back to callouts page

.github/workflows/release.yml
There is a new repository variable, AZ_DISPATCH_TO, holding the list of repositories targeted by the repository dispatch mechanism on a new release.
The communication mechanism between release workflow jobs uses the outputs mechanism, as opposed to the artifact upload & download.
Closes #921
Closes #993
=> Closes #921, Closes #993: Various improvements to GH actions release workflow.

scss/legacy/_mixins.scss
This PR removes the alert-variant() mixin from the legacy mixins. We don't need it in Arizona Bootstrap 5 and it was never used in Arizona Bootstrap 2: the import of the custom alert styling was commented out in the main scss file:
https://github.com/az-digital/arizona-bootstrap/blob/2.x/scss/arizona-bootstrap.scss#L60
Arizona Bootstrap 5 will not contain any customizations specific to the Alerts component.
Review site: https://review.digital.arizona.edu/arizona-bootstrap/issue/1574/docs/5.0/components/alerts/
Arizona Bootstrap 2: https://digital.arizona.edu/arizona-bootstrap/docs/2.0/components/alerts/
=> Closes #1574: Remove unused alerts customization in Arizona Bootstrap 5

site/content/docs/5.0/backwards-compatibility.md
Moves our current documentation for upgrading the accordion component from AZBS2 to AZBS5. See #1614 
1. Compare the [new text and location](https://review.digital.arizona.edu/arizona-bootstrap/issue/1614/docs/5.0/backwards-compatibility/#accordion-implementation) to the [old](https://review.digital.arizona.edu/arizona-bootstrap/main/docs/5.0/backwards-compatibility/#accordion). The code block and example have been removed. Text is the same.
=> Closes 1614: Improve upgrade documentation for accordion component

scss/custom/_photo-gallery.scss, site/content/docs/5.0/components/photo-gallery.md
- Updates Photo Gallery custom styling to ensure portrait images are cropped in the Photo Gallery Slider Crop style
- Removes unnecessary `.az-gallery-item` class (which had no CSS associated with it) from Photo Gallery HTML
- https://review.digital.arizona.edu/arizona-bootstrap/issue/1646/docs/5.0/components/photo-gallery
Compare with main branch:
- https://review.digital.arizona.edu/arizona-bootstrap/main/docs/5.0/components/photo-gallery
=> Closes #1646: Portrait images are not cropped correctly in Photo Galleries with Slider Crop style

site/content/docs/5.0/content/typography.md
- Updates the Typography docs page to use the custom AZ Bootstrap badge in the section for the custom triangles class
- https://review.digital.arizona.edu/arizona-bootstrap/issue/1651/docs/5.0/content/typography/#triangles
1. Should we deprecate/remove `.ul-triangles` and change that class to `.list-triangles` or `.az-list-triangles` to match the upstream Bootstrap list classes?
=> Closes #1651: Update "Custom Arizona Bootstrap Class" styling on Typography page

build/vnu-jar.mjs
I believe this should resolve the lint errors in the PR checks for #1666:
```
Running vnu-jar validation...
command used: java -jar "/arizona-bootstrap-source/node_modules/vnu-jar/build/dist/vnu.jar" --asciiquotes --skip-non-html --Werror --filterpattern "Attribute “autocomplete” is only allowed when the input type is.*|Attribute “autocomplete” not allowed on element “button” at this point.|An “aria-disabled” attribute whose value is “true” should not be specified on an “a” element that has an “href” attribute." _site/ js/tests/
ERROR: "docs-vnu" exited with 1.
ERROR: "docs-lint" exited with 1.
Error: Process completed with exit code 1.
```
=> #1665: Add ignore line for hash placeholder values back to vnu_jar.mjs script.

site/content/docs/5.0/helpers/color-background.md
Closes #1673
Adds a note about the `bg-transparent` class to the Color & Background page
Review site: https://review.digital.arizona.edu/arizona-bootstrap/issue/1673/docs/5.0/helpers/color-background/#transparent
=> Closes #1673: Adds note about bg-transparent class to Color & Background page

scss/override/_variables.scss
Closes #1689
Updates pagination's focus and active colors to blue
https://review.digital.arizona.edu/arizona-bootstrap/issue/1689/docs/5.0/components/pagination/
1. Ensure active and focus colors are now blue
2. Ensure other components are not negatively effected
=> Closes #1689: Update pagination focus and active colors to blue

scss/custom/_arizona-header.scss
- Updates Arizona Header styling to set all content to `justify-content: end`, to align all items to the right.
- Updates the `.arizona-logo` class to keep the university wordmark logo aligned to the left. The wordmark logo is the ONLY item that should be aligned to the left.
https://review.digital.arizona.edu/arizona-bootstrap/issue/1712/docs/5.0/components/arizona-header/
1. Confirm that the Arizona Header examples look the same as before.
2. Inspect the page and try deleting the `d-lg-none` class for the buttons to confirm that content would be right-aligned on desktop as well.
3. Try deleting the wordmark logo to ensure that the buttons remain aligned to the right.
=> Closes #1712: Right-justify content in the Arizona Header except for the wordmark logo

scss/custom/_arizona-header.scss
- Sets the border radius to 0 for the `.btn-arizona-header` class (overriding the default border radius for buttons)
1. Go to https://review.digital.arizona.edu/arizona-bootstrap/issue/1742/docs/5.0/components/arizona-header/#extending-the-header
2. Resize your browser window until the mobile header buttons are visible
3. Hold the mouse down over the buttons to confirm that the white border for the active state has sharp corners rather than rounded corners
=> Closes #1742: Update Arizona Header buttons to have sharp corners
