az-digital/arizona-bootstrap

LICENSE
=> Modified format of license file to improve GitHub license detection.

.github/workflows/review-site.yml, package.json, scripts/build-review-site.sh
MVP GitHub actions for PRs created during 2020-04-15 workshop.  Fixes #58.
=> Review sites using GitHub Actions

.github/workflows/lint.yml, package.json, scripts/lint.sh
This is untested/WIP but I wanted to get something up before our 2020-04-29 workshop.
=> Closes #69: Added GitHub actions workflow for code linting.

package-lock.json, package.json
This updates Arizona Bootstrap to version 0.0.4
=> Release 0.0.4

.github/workflows/cdn-deploy.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/review-site.yml, Dockerfile, Gemfile.lock, package-lock.json, package.json, scripts/build-container.sh
Depends indirectly on the feature/109 changes (based on that branch).
=> Include more files on the checksum used as a Docker image tag — Closes #111

.github/workflows/cdn-deploy.yml, .github/workflows/release.yml
See https://github.com/az-digital/arizona-bootstrap/issues/131
=> Use repository_dispatch

.github/dependabot.yml
=> change dependabot to check monthly

site/docs/2.0/components/card.md
Copied upstream fix from this [TWBS PR](https://github.com/twbs/bootstrap/pull/30925)
=> Closes #180: Fix incorrect markup in image cap bottom card example.

scss/_navbar-offcanvas.scss
Made changes suggested by @akslay to fix off-canvas navigation bugs seen on in-devlopment Registrar website.
=> Closes #223: Fixes for various off-canvas navigation bugs.

site/content/docs/2.0/icons.md
Pinned and Latest releases are not available yet, but the wording is there to inform which to use once they are available.
=> Closes #362: Add some documentation about which version of az-icons to use

scss/_custom-variables.scss, site/content/docs/2.0/utilities/spacing.md
Closes #375 
Intent: Have larger spacing options to use with the Text on media and Text with background paragraph types
Review site: https://review.digital.arizona.edu/arizona-bootstrap/issue/375/docs/2.0/utilities/spacing/
=> Closes #375: Add larger spacing options

site/content/docs/2.0/content/font.md
Closes #529 
Remove outdated text and add additional notes about the license and recommendations for how to manage fonts.
=> Closes #529 Update advantages and disadvantages of managing fonts.

site/content/docs/2.0/components/breadcrumb.md, site/content/docs/2.0/components/collapse.md, site/layouts/partials/alert-warning-material-design.md, site/layouts/shortcodes/alert.html
https://review.digital.arizona.edu/arizona-bootstrap/issue/1825-breadcrumbs-documentation/docs/2.0/components/breadcrumb/
https://review.digital.arizona.edu/arizona-bootstrap/issue/1825-breadcrumbs-documentation/docs/2.0/components/collapse/
=> Update breadcrumbs documentation

.github/workflows/release.yml, .github/workflows/review-site.yml
The Action depends on https://github.com/az-digital/digital.arizona.edu/pull/36
=> Closes #563: Copy the file ownership fix-up from the Action that builds review sites on PRs.

.github/workflows/review-site.yml
Tested successfully in the throwaway PR https://github.com/az-digital/arizona-bootstrap/pull/574
=> Closes #575: Increase the number of commits available to the Action that pushes modified CSS or JS files.

.github/workflows/review-site.yml
Created token in repo that can be used by dependabot or a pull requestor for updating the docker container registry.
=> Closes #870 Update token name so we can use a token of our own.

Dockerfile, package-lock.json, site/content/docs/5.0/examples/navbar/index.html, site/content/docs/5.0/utilities/colors.md
A further repeat of #1072 applying the changes in brand.arizona.edu links to marcom.arizona.edu links in the main branch.
=> Closes #1074: apply the brand to marcom name change to the main branch.

Dockerfile, package-lock.json
The Dockerfile changes are significant, the lockfile changes incidental.
=> Closes #1228: Backport the Dockerfile changes from the main branch.

.github/workflows/review-site.yml
=> Close #1284 update how we log into the docker container registry.

site/content/docs/5.0/utilities/colors.md
This pull request is a branch of this PR:
- #1443 
This pull request simply updates the Colors page under Utilities in the docs.
After merging, I think #1443 should close issue #1401 as well.
=> [Branch of issue/1419] Update Colors docs page

.github/workflows/review-site.yml
=> #1526: Remove the --force on the GitHub Actions push of changes back to the repository. (2.x)
